apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-frontend-kube
  labels:
    app: product-frontend-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-frontend-kube
  template:
    metadata:
      labels:
        app: product-frontend-kube
    spec:
      containers:
      - name: product-frontend-kube
        image: amnashahid/react-fe-img-22