version: '3.4'

volumes:
  datafiles:


services:
  mysqldb:
    image: mysql:8.0.22
    ports:
      - "1336:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always

    environment:
      MYSQL_PASSWORD: sa
  #Api  Service
  api:
    image: amnashahid/devops-be
    build:
      context: .
    depends_on:
      - mysqldb
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  #frontend
  app:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
